steps:
  # Step 0: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        set -e
        echo "Starting Docker build..."
        docker build \
          -t us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:$SHORT_SHA \
          -t us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:latest \
          -f Dockerfile .
    entrypoint: bash

  # Step 1: Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend

  # Step 2: Deploy to VM (The 1:1 Logic Replication)
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        set -e
        echo "Deploying to VM..."

        gcloud compute ssh tooryst-backend-vm \
          --zone=us-central1-c \
          --command "
            set -e

            # 1. AUTHENTICATE
            sudo gcloud auth configure-docker us-central1-docker.pkg.dev -q

            # 2. NUCLEAR CLEANUP (Fixes the Zombie issue)
            # Stops and removes ANY container with 'tooryst' in the name
            echo 'Stopping all existing Tooryst containers...'
            sudo docker ps -a --filter name=tooryst -q | xargs -r sudo docker rm -f
            
            # Prune old images to save space
            sudo docker image prune -af

            # 3. PULL NEW IMAGE
            echo 'Pulling latest image...'
            sudo docker pull us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:$SHORT_SHA

            # 4. START BACKEND API (Matches 'Starting Backend API...')
            echo 'Starting Backend API...'
            sudo docker run -d \
              --network host \
              --name tooryst-backend \
              --restart unless-stopped \
              --env-file /home/thebettervacation_com/.env \
              us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:$SHORT_SHA

            # 5. START CELERY BEAT (Matches 'Starting Celery Beat...')
            echo 'Starting Celery Beat...'
            sudo docker run -d \
              --network host \
              --name tooryst-celery-beat \
              --restart unless-stopped \
              --env-file /home/thebettervacation_com/.env \
              us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:$SHORT_SHA \
              celery -A app.celery_app:celery_app beat --loglevel=INFO

            # 6. START CELERY MAIN WORKER (Matches 'Main Pipeline Worker')
            # Handles 'pipeline' and 'celery' queues
            echo 'Starting Main Worker...'
            sudo docker run -d \
              --network host \
              --name tooryst-celery-main \
              --restart unless-stopped \
              --env-file /home/thebettervacation_com/.env \
              us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:$SHORT_SHA \
              celery -A app.celery_app:celery_app worker -Q pipeline,celery -c 4 -n main@%h --loglevel=INFO

            # 7. START STAGE WORKERS 1-10 (Matches Stages 1-10 logic)
            # Loops 1 through 10 creating a unique container for each
            echo 'Starting Stage Workers 1-10...'
            for i in {1..10}; do
              sudo docker run -d \
                --network host \
                --name tooryst-celery-stage\$i \
                --restart unless-stopped \
                --env-file /home/thebettervacation_com/.env \
                us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:$SHORT_SHA \
                celery -A app.celery_app:celery_app worker -Q pipeline_stage_\$i -c 1 -n stage\$i@%h --loglevel=INFO
            done

            # 8. VERIFICATION
            echo 'Waiting for services to initialize...'
            sleep 5
            
            echo 'Running Health Check...'
            if curl -fsS http://127.0.0.1:8000/api/v1/health >/dev/null; then
               echo '✓ Backend Health: OK'
            else
               echo 'WARNING: Backend Health check failed.'
            fi

            echo 'Deployment Complete. Active Containers:'
            sudo docker ps --filter name=tooryst --format 'table {{.Names}}\t{{.Status}}\t{{.Command}}'
          "
    entrypoint: bash

images:
  - 'us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/toorists/tooryst-repo-backend/backend:latest'

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY